/**
 * generate-audio.mjs — PracticeEnglish Audio Generator
 * ======================================================
 * Checks ALL audio sources and generates any missing WAV files using
 * Kokoro-82M TTS. Existing files are always skipped — safe to re-run
 * at any time, including after adding or editing phrases.
 *
 * STALE AUDIO DETECTION
 * ─────────────────────
 * Audio files are named by slug ({audioSlug}-{voice}.wav). The slug is
 * derived from the phrase or word text and stored in the JSON. Position
 * shifts in the JSON array have no effect on audio files — only text
 * changes cause new files to be generated.
 *
 * When a phrase or word text changes, the slug changes, the old file
 * becomes an orphan (it is simply ignored by the generator), and a new
 * file is generated automatically as a missing file. Run with --prune
 * (future flag) to clean up orphaned files.
 *
 * SOURCES covered:
 *   Phrase topics  → shared/audio/es-en/{topic}/{audioSlug}-{voice}.wav  (EN target)
 *   Vocab general  → shared/audio/vocab/{wordId}-{voice}.wav
 *   Vocab topics   → shared/audio/vocab_{topic}/{wordId}-{voice}.wav
 *
 * USAGE (run from the tools/ directory):
 *   node generate-audio.mjs                  # check + generate everything
 *   node generate-audio.mjs --check          # dry-run: report missing + stale
 *   node generate-audio.mjs --topic greetings          # single phrase topic
 *   node generate-audio.mjs --topic vocab              # general vocab only
 *   node generate-audio.mjs --topic vocab_greetings    # topic vocab only
 *
 * VOICES generated (edit VOICES below to change):
 *   af_heart · af_bella · bf_emma · am_michael
 *
 * REQUIREMENTS:
 *   - Node.js ≥ 18
 *   - kokoro-js installed (npm install in tools/)
 *   - Run from the tools/ directory so relative paths resolve correctly
 */

import { KokoroTTS } from 'kokoro-js';
import { readFileSync, existsSync, mkdirSync, writeFileSync, unlinkSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Slug helper (mirrors slugify in assign-alt-slugs.mjs) ──────────────────
// Capped at SLUG_MAX with an 8-char sha256 suffix when exceeded — keeps audio
// paths within Windows MAX_PATH (260). Must stay identical across the 3 tools.
const SLUG_MAX = 100;
const _slugBase = s =>
  s.toLowerCase()
   .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
   .replace(/[^a-z0-9]+/g, '_')
   .replace(/^_|_$/g, '');
const slugify = s => {
  const base = _slugBase(s);
  if (base.length <= SLUG_MAX) return base;
  const hash = createHash('sha256').update(s, 'utf8').digest('hex').slice(0, 8);
  const head = base.slice(0, SLUG_MAX - 9).replace(/_+$/, '');
  return `${head}_${hash}`;
};

// ── Configuration ──────────────────────────────────────────────────────────

/**
 * Voice IDs per target language code.
 * Add a new entry here when a new language pair is introduced.
 * Key = ISO 639-1 target language code (must match pair.target.code in lang-pair.js).
 *
 * Languages handled by Kokoro-82M (generated here):
 *   en  American/British English
 *   fr  French
 *   it  Italian
 *   pt  Brazilian Portuguese
 *
 * Languages handled by generate-audio-tgt.py (edge-tts / Azure Neural TTS):
 *   es  Spanish          de  German         nl  Dutch
 *   pl  Polish           sv  Swedish         no  Norwegian
 *   da  Danish           fi  Finnish         cs  Czech
 *   lv  Latvian          lt  Lithuanian      et  Estonian
 * These are registered here so --topic filter and LANG_VOICE_LEADERS work correctly;
 * they are skipped by the Kokoro generator (edgeTts: true).
 */
const LANG_VOICES = {
  en: ['af_heart', 'af_bella', 'bf_emma', 'am_michael'],
  es: ['ef_dora',  'em_alex',  'em_santa'],
  fr: ['ff_siwis', 'fm_gaston'],
  de: ['df_hedda', 'dm_bernd'],
  it: ['if_sara',  'im_nicola'],
  pt: ['pf_dora',  'pm_alex',  'pm_santa'],
  nl: ['nlf_colette', 'nlm_maarten'],
  pl: ['plf_zofia',   'plm_marek'],
  sv: ['svf_sofie',   'svm_mattias'],
  no: ['nof_pernille','nom_finn'],
  da: ['daf_christel','dam_jeppe'],
  fi: ['fif_selma',   'fim_harri'],
  cs: ['csf_vlasta',  'csm_antonin'],
  lv: ['lvf_everita', 'lvm_nils'],
  lt: ['ltf_ona',     'ltm_leonas'],
  et: ['etf_anu',     'etm_kert'],
};

/**
 * Languages whose audio is generated by generate-audio-tgt.py (edge-tts / Azure Neural)
 * rather than by Kokoro. Sources for these langs are registered in ALL_SOURCES for
 * --topic error messages but are excluded from Kokoro generation.
 */
const EDGE_TTS_LANGS = new Set(['es','de','nl','pl','sv','no','da','fi','cs','lv','lt','et']);

/** Convenience: English voices */
const VOICES_EN = LANG_VOICES.en;
/** Default voice set */
const VOICES = VOICES_EN;
const MODEL  = 'onnx-community/Kokoro-82M-v1.0-ONNX';
const DTYPE  = 'fp32';   // 'q8' is faster but lower quality
const SPEED  = 0.95;

const MANIFEST_PATH = resolve(__dirname, '../shared/audio/.manifest.json');

/** All phrase topic IDs (each maps to shared/json/{id}.json) */
const PHRASE_TOPICS = [
  'emociones', 'greetings', 'restaurant', 'supermarket', 'kitchen',
  'transportation', 'airport', 'accommodation',
  'movies', 'music', 'theater', 'museums',
  'gym', 'technology', 'accountability', 'personal_info',
];

/** All vocabulary topic IDs (each maps to shared/json/pairs/{pairId}/vocab/words-{id}.json) */
const VOCAB_TOPICS = [
  'emociones', 'greetings', 'restaurant', 'supermarket', 'kitchen',
  'transportation', 'airport', 'accommodation',
  'movies', 'music', 'theater',
  'gym', 'technology', 'accountability',
];

// ── Parse CLI arguments ────────────────────────────────────────────────────

const args      = process.argv.slice(2);
const checkOnly = args.includes('--check');
const topicArg  = args.includes('--topic') ? args[args.indexOf('--topic') + 1] : null;
const langArg   = args.includes('--lang')  ? args[args.indexOf('--lang')  + 1] : null;

// ── Helpers for alternative audio ─────────────────────────────────────────

/**
 * Flatten typed, non-style alternatives from the per-pair schema.
 * Reads p.target[i] (i >= 1) where audioSlug is defined.
 * Only entries that already have an audioSlug are included.
 */
function flattenAlts(data) {
  const alts = [];
  for (const p of data.phrases ?? []) {
    const target = p.target ?? [];
    for (let i = 1; i < target.length; i++) {
      const item = target[i];
      if (typeof item === 'object' && item.audioSlug !== undefined)
        alts.push({ audioSlug: item.audioSlug, text: item.text, id: `alt_${item.audioSlug}` });
    }
  }
  return alts;
}

// ── Build source list ──────────────────────────────────────────────────────

/**
 * Each source has:
 *   id        — unique key used for --topic / --lang filter and manifest key
 *   jsonPath  — path to the JSON file
 *   outDir    — directory where WAV files are written
 *   getItems  — function(data) → array of items
 *   getText   — function(item) → string to synthesize
 *   getId     — function(item) → stable ID string (used by manifest)
 *   voices    — Kokoro voice IDs for this source
 *   edgeTts   — true = handled by generate-audio-tgt.py, skip here
 *   noManifest — true = slug-based sources (no position-based stale detection needed)
 *   getIndex  — function(item) → audio slug string used as filename prefix
 *
 * Sources are built dynamically from LANG_VOICES so that adding a new language
 * pair only requires adding an entry to LANG_VOICES — no other code change needed.
 */
const ALL_SOURCES = [];

// ── English phrase sources ───────────────────────────────────────────────────
// English (Kokoro voices) is the target language only for these pairs. Add a
// pair id here if a new pair whose target is English is introduced (e.g. fr-en);
// no other change is needed.
const EN_TARGET_PAIRS = ['es-en'];

EN_TARGET_PAIRS.forEach(pair => {
  PHRASE_TOPICS.forEach(id => {
    ALL_SOURCES.push({
      id:         `${pair}__${id}`,
      jsonPath:   resolve(__dirname, `../shared/json/pairs/${pair}/${id}.json`),
      outDir:     resolve(__dirname, `../shared/audio/${pair}/${id}`),
      getItems:   data => data.phrases || [],
      getText:    item => item.target?.[0]?.text || '',
      getId:      item => item.id,
      getIndex:   item => item.target?.[0]?.audioSlug || slugify(item.target?.[0]?.text || item.id),
      voices:     VOICES_EN,
      noManifest: true,
    });
    ALL_SOURCES.push({
      id:         `${pair}__${id}__alts`,
      jsonPath:   resolve(__dirname, `../shared/json/pairs/${pair}/${id}.json`),
      outDir:     resolve(__dirname, `../shared/audio/${pair}/${id}`),
      getItems:   data => flattenAlts(data),
      getText:    item => item.text,
      getId:      item => item.id,
      getIndex:   item => item.audioSlug,
      voices:     VOICES_EN,
      noManifest: true,
    });
  });
});
ALL_SOURCES.push({
  id:         'vocab',
  jsonPath:   resolve(__dirname, '../shared/json/pairs/es-en/vocab/words.json'),
  outDir:     resolve(__dirname, '../shared/audio/es-en/vocab'),
  getItems:   data => data.words || [],
  getText:    item => item.word,
  getId:      item => item.id,
  getIndex:   item => item.id,
  voices:     VOICES_EN,
  noManifest: true,
});
VOCAB_TOPICS.forEach(id => {
  ALL_SOURCES.push({
    id:         `vocab_${id}`,
    jsonPath:   resolve(__dirname, `../shared/json/pairs/es-en/vocab/words-${id}.json`),
    outDir:     resolve(__dirname, `../shared/audio/es-en/vocab_${id}`),
    getItems:   data => data.words || [],
    getText:    item => item.word,
    getId:      item => item.id,
    getIndex:   item => item.id,
    voices:     VOICES_EN,
    noManifest: true,
  });
});

// ── Non-English phrase sources ────────────────────────────────────────────
// Handled by generate-audio-tgt.py (edge-tts) which reads from the per-pair
// JSON directory and writes to shared/audio/{pairId}/{topic}/.
// Register as edge-tts stubs so --topic error messages remain helpful.
for (const [langCode, voices] of Object.entries(LANG_VOICES)) {
  if (langCode === 'en') continue;
  const isEdge = EDGE_TTS_LANGS.has(langCode);
  const suffix = `__${langCode}`;

  PHRASE_TOPICS.forEach(id => {
    ALL_SOURCES.push({
      id: `${id}${suffix}`,
      // Inert stub — getItems returns [] so jsonPath is never read; it exists
      // only so --topic matching and error messages stay helpful. The real
      // generation for these languages is done by generate-audio-tgt.py.
      jsonPath: resolve(__dirname, `../shared/json/pairs/en-${langCode}/${id}.json`),
      outDir:   resolve(__dirname, `../shared/audio/${id}`),
      getItems: () => [],
      getText:  () => '',
      getId:    () => '',
      voices,
      edgeTts:  isEdge,
    });
  });

  ALL_SOURCES.push({
    id:         `vocab${suffix}`,
    jsonPath:   resolve(__dirname, `../shared/json/pairs/en-${langCode}/vocab/words.json`),
    outDir:     resolve(__dirname, `../shared/audio/en-${langCode}/vocab`),
    getItems:   data => (data.words || []).filter(w => w.translations?.[langCode]),
    getText:    item => item.translations[langCode],
    getId:      item => item.id,
    getIndex:   item => item.id,
    voices,
    edgeTts:    isEdge,
    noManifest: true,
  });
  VOCAB_TOPICS.forEach(id => {
    ALL_SOURCES.push({
      id:         `vocab_${id}${suffix}`,
      jsonPath:   resolve(__dirname, `../shared/json/pairs/en-${langCode}/vocab/words-${id}.json`),
      outDir:     resolve(__dirname, `../shared/audio/en-${langCode}/vocab_${id}`),
      getItems:   data => (data.words || []).filter(w => w.translations?.[langCode]),
      getText:    item => item.translations[langCode],
      getId:      item => item.id,
      getIndex:   item => item.id,
      voices,
      edgeTts:    isEdge,
      noManifest: true,
    });
  });
}

// ── Source filtering ───────────────────────────────────────────────────────

const KOKORO_SOURCES = ALL_SOURCES.filter(s => !s.edgeTts);
const EDGE_SOURCES   = ALL_SOURCES.filter(s =>  s.edgeTts);
// EN-only sources: no __lang suffix on the base phrase/vocab IDs
const EN_ONLY_SOURCES = KOKORO_SOURCES.filter(s => !s.id.match(/__[a-z]{2}(__alts)?$/));

// Default: process EN only (same as before adding multi-lang support).
// Use --lang <code> to process a specific target language instead.
let sources = EN_ONLY_SOURCES;

if (langArg) {
  if (langArg === 'en') {
    sources = EN_ONLY_SOURCES;
  } else if (EDGE_TTS_LANGS.has(langArg)) {
    console.error(`"${langArg}" uses edge-tts — run: python generate-audio-tgt.py --lang ${langArg}`);
    process.exit(1);
  } else {
    sources = KOKORO_SOURCES.filter(s =>
      s.id.endsWith(`__${langArg}`) || s.id.endsWith(`__${langArg}__alts`));
    if (sources.length === 0) {
      const known = Object.keys(LANG_VOICES).filter(l => !EDGE_TTS_LANGS.has(l)).join(', ');
      console.error(`Unknown language: "${langArg}". Kokoro languages: ${known}`);
      process.exit(1);
    }
  }
}

if (topicArg) {
  // Accept both bare topic name (e.g. 'greetings') and full source ID (e.g. 'es-en__greetings')
  sources = sources.filter(s =>
    s.id === topicArg ||
    s.id === `es-en__${topicArg}` ||
    s.id === `es-en__${topicArg}__alts` ||
    s.id === topicArg + '__alts'
  );
  if (sources.length === 0) {
    const edgeMatch = EDGE_SOURCES.some(s => s.id === topicArg || s.id.startsWith(topicArg + '__'));
    if (edgeMatch) {
      const m = topicArg.match(/__([a-z]{2,})(__alts)?$/);
      const lang = m ? m[1] : 'es';
      const baseTopic = topicArg.replace(`__${lang}`, '');
      console.error(`"${topicArg}" uses edge-tts — run: python generate-audio-tgt.py --lang ${lang} --topic ${baseTopic}`);
    } else {
      console.error(`Unknown topic: "${topicArg}". Valid IDs:\n  ${KOKORO_SOURCES.map(s => s.id).join('\n  ')}`);
    }
    process.exit(1);
  }
}

if (!topicArg && !langArg) {
  if (EDGE_SOURCES.length > 0) {
    const edgeLangs = [...EDGE_TTS_LANGS].join(', ');
    console.log(`ℹ  Edge-TTS sources skipped — run: python generate-audio-tgt.py --lang ${edgeLangs}`);
  }
  const kokoroLangs = Object.keys(LANG_VOICES).filter(l => l !== 'en' && !EDGE_TTS_LANGS.has(l));
  if (kokoroLangs.length > 0)
    console.log(`ℹ  Other Kokoro languages available: ${kokoroLangs.join(', ')} — run with --lang <code> to generate`);
}

// ── Manifest helpers ───────────────────────────────────────────────────────

/**
 * A manifest entry encodes both the stable ID and the synthesized text so
 * that edits to the text of an existing item are also detected as stale.
 * Format: "id\x00text"  (null byte separator — never appears in IDs or text)
 */
function makeSignature(item, src) {
  return `${src.getId(item)}\x00${src.getText(item)}`;
}

function sigId(sig)   { return sig.split('\x00')[0]; }
function sigText(sig) { return sig.split('\x00')[1] ?? ''; }

// ── Load manifest ──────────────────────────────────────────────────────────

let manifest = {};
if (existsSync(MANIFEST_PATH)) {
  try { manifest = JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')); }
  catch { console.warn('  [warn] Could not read manifest — skipping stale detection for this run.'); }
}

// ── Stale detection + cleanup (or dry-run report) ─────────────────────────

let totalStaleRemoved  = 0;
let totalStaleReported = 0;

for (const src of sources) {
  if (src.noManifest) continue;   // slug-based sources skip manifest (no position-based stale detection)
  if (!existsSync(src.jsonPath)) continue;

  const data      = JSON.parse(readFileSync(src.jsonPath, 'utf8'));
  const items     = src.getItems(data);
  const currentSigs = items.map(item => makeSignature(item, src));
  const oldSigs     = manifest[src.id] || [];

  // Positions that exist in old manifest with a different signature → stale
  // (catches: position shifts, ID changes, and text edits of existing items)
  const stalePositions = [];
  for (let i = 0; i < oldSigs.length; i++) {
    const currentSig = currentSigs[i];     // undefined if array shrank
    if (currentSig === undefined || currentSig !== oldSigs[i]) {
      stalePositions.push(i);
    }
  }

  if (stalePositions.length === 0) continue;

  if (checkOnly) {
    for (const i of stalePositions) {
      const oldSig = oldSigs[i];
      const cur    = currentSigs[i];
      const oldLabel = `${sigId(oldSig)} "${sigText(oldSig).slice(0, 40)}"`;
      const newLabel = cur ? `${sigId(cur)} "${sigText(cur).slice(0, 40)}"` : '(removed)';
      const oldSlugReport = sigText(oldSigs[i]) ? slugify(sigText(oldSigs[i])) : String(i);
      console.log(`  [stale] ${src.id}/${oldSlugReport}-*.wav`);
      console.log(`          was: ${oldLabel}`);
      console.log(`          now: ${newLabel}`);
      totalStaleReported += (src.voices || VOICES).length;
    }
  } else {
    let srcStale = 0;
    for (const i of stalePositions) {
      const oldSig   = oldSigs[i];
      const oldSlug  = sigText(oldSig) ? slugify(sigText(oldSig)) : String(i);
      for (const voice of (src.voices || VOICES)) {
        const stalePath = resolve(src.outDir, `${oldSlug}-${voice}.wav`);
        if (existsSync(stalePath)) { unlinkSync(stalePath); srcStale++; }
      }
    }
    if (srcStale > 0) {
      console.log(`  [${src.id}] Removed ${srcStale} stale file(s) at ${stalePositions.length} position(s)`);
      totalStaleRemoved += srcStale;
    }
  }
}

// ── Collect missing tasks ──────────────────────────────────────────────────

const tasks = [];
let totalExpected = 0;

for (const src of sources) {
  if (!existsSync(src.jsonPath)) {
    console.warn(`  [skip] JSON not found: ${src.jsonPath}`);
    continue;
  }

  const data  = JSON.parse(readFileSync(src.jsonPath, 'utf8'));
  const items = src.getItems(data);

  mkdirSync(src.outDir, { recursive: true });

  for (let i = 0; i < items.length; i++) {
    for (const voice of (src.voices || VOICES)) {
      totalExpected++;
      const fileIdx = src.getIndex ? src.getIndex(items[i]) : i;
      const outPath = resolve(src.outDir, `${fileIdx}-${voice}.wav`);
      if (!existsSync(outPath)) {
        tasks.push({ src: src.id, i: fileIdx, voice, text: src.getText(items[i]), outPath });
      }
    }
  }
}

// ── Report ─────────────────────────────────────────────────────────────────

const existing = totalExpected - tasks.length;
console.log(`\nAudio check complete`);
const voiceSummary = Object.entries(LANG_VOICES).map(([l, v]) => `${l}:${v.length}`).join(' ');
console.log(`  Expected : ${totalExpected} files (${sources.length} source(s) — voices: ${voiceSummary})`);
console.log(`  Existing : ${existing}`);
console.log(`  Missing  : ${tasks.length}`);
if (totalStaleRemoved  > 0) console.log(`  Stale removed  : ${totalStaleRemoved}`);
if (totalStaleReported > 0) console.log(`  Stale detected : ${totalStaleReported} (dry-run — run without --check to fix)`);

if (tasks.length === 0 && totalStaleReported === 0) {
  console.log('\nAll audio files are up to date.');

  // Always write manifest on a clean run (even if nothing changed) to keep it fresh
  if (!checkOnly) _writeManifest();

  process.exit(0);
}

if (checkOnly) {
  if (tasks.length > 0) {
    console.log('\nMissing files:');
    for (const t of tasks) {
      console.log(`  ${t.src}/${t.i}-${t.voice}.wav  — "${t.text.slice(0, 60)}"`);
    }
  }
  console.log('\n(dry-run — pass without --check to generate)');
  process.exit(0);
}

// ── Generate ───────────────────────────────────────────────────────────────

console.log(`\nLoading Kokoro-82M (dtype=${DTYPE})…`);
const tts = await KokoroTTS.from_pretrained(MODEL, { dtype: DTYPE });
console.log('Model ready.\n');

/** Encode Float32 PCM → 16-bit WAV Buffer */
function encodeWav(samples, sampleRate) {
  const numSamples = samples.length;
  const byteCount  = numSamples * 2;
  const buf        = Buffer.alloc(44 + byteCount);
  buf.write('RIFF', 0); buf.writeUInt32LE(36 + byteCount, 4); buf.write('WAVE', 8);
  buf.write('fmt ', 12); buf.writeUInt32LE(16, 16); buf.writeUInt16LE(1, 20); buf.writeUInt16LE(1, 22);
  buf.writeUInt32LE(sampleRate, 24); buf.writeUInt32LE(sampleRate * 2, 28);
  buf.writeUInt16LE(2, 32); buf.writeUInt16LE(16, 34);
  buf.write('data', 36); buf.writeUInt32LE(byteCount, 40);
  for (let i = 0; i < numSamples; i++) {
    const s = Math.max(-1, Math.min(1, samples[i]));
    buf.writeInt16LE(Math.round(s * 32767), 44 + i * 2);
  }
  return buf;
}

let generated = 0;
let errors    = 0;

for (const { src, i, voice, text, outPath } of tasks) {
  const label = `[${generated + errors + 1}/${tasks.length}] ${src}/${i}-${voice}.wav`;
  process.stdout.write(`${label} — "${text.slice(0, 50)}"… `);
  try {
    const result = await tts.generate(text, { voice, speed: SPEED });
    writeFileSync(outPath, encodeWav(result.audio, result.sampling_rate));
    console.log('✓');
    generated++;
  } catch (e) {
    console.log(`✗  ${e.message}`);
    errors++;
  }
}

console.log(`\nDone — ${generated} generated, ${errors} errors, ${existing} already existed.`);

// Write manifest after successful generation
if (errors === 0) _writeManifest();

if (errors > 0) process.exit(1);

// ── Manifest writer ────────────────────────────────────────────────────────

function _writeManifest() {
  // Update only the sources that were processed in this run
  for (const src of sources) {
    if (src.noManifest) continue;   // slug-based sources — no position-based stale detection
    if (!existsSync(src.jsonPath)) continue;
    const data  = JSON.parse(readFileSync(src.jsonPath, 'utf8'));
    const items = src.getItems(data);
    manifest[src.id] = items.map(item => makeSignature(item, src));
  }
  writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2));
}
