/* ============================================================
   audio-player.js — Static audio file player with Kokoro fallback

   Primary path: fetches pre-generated WAV files from disk.
   Fallback: Kokoro (AppTTS) for any phrase not yet pre-generated.

   Usage:
     AppAudio.setBase('../audio/');           // call once per page
     AppAudio.play(topic, index, text)        // speaking (normal speed)
     AppAudio.play(topic, index, text, 0.9)  // dictation (slower playback)
     AppAudio.cancel()
     AppAudio.warmup()
   ============================================================ */
const AppAudio = (() => {

  // Voices to pick from randomly — must match what was generated by the tool.
  // Keep in sync with VOICE_CATALOG defaults in tools/generate-audio.html.
  const VOICES = ['af_heart', 'af_bella', 'bf_emma', 'am_michael'];

  let _base          = '../audio/';   // path to {topic}/{index}_{voice}.wav, relative to the page
  let _audioCtx      = null;
  let _currentSource = null;
  let _cancelId      = 0;             // incremented on every play()/cancel() call

  function setBase(base) { _base = base; }

  function _getCtx() {
    if (!_audioCtx || _audioCtx.state === 'closed') _audioCtx = new AudioContext();
    return _audioCtx;
  }

  function _randomVoice() {
    return VOICES[Math.floor(Math.random() * VOICES.length)];
  }

  /**
   * Play pre-generated audio for a phrase.
   * @param {string}  topic       - e.g. 'greetings'
   * @param {number}  index       - phrase index in the topic JSON
   * @param {string}  text        - phrase text (used by Kokoro fallback)
   * @param {number}  [rate=1.0]  - playback rate (0.9 for dictation)
   */
  async function play(topic, index, text, rate) {
    cancel();
    const myId  = ++_cancelId;
    const speed = rate || 1.0;
    const voice = _randomVoice();
    const url   = _base + topic + '/' + index + '_' + voice + '.wav';

    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error('not found');
      if (_cancelId !== myId) return;

      const arrayBuf = await res.arrayBuffer();
      if (_cancelId !== myId) return;

      const ctx    = _getCtx();
      const audioBuf = await ctx.decodeAudioData(arrayBuf);
      if (_cancelId !== myId) return;

      return new Promise((resolve) => {
        const src = ctx.createBufferSource();
        src.buffer = audioBuf;
        src.playbackRate.value = speed;
        src.connect(ctx.destination);
        src.onended = () => { _currentSource = null; resolve(); };
        _currentSource = src;
        const start = () => src.start();
        if (ctx.state === 'suspended') ctx.resume().then(start).catch(resolve);
        else start();
      });

    } catch {
      // Static file not available — fall back to Kokoro
      if (_cancelId !== myId) return;
      if (typeof AppTTS === 'undefined') return;
      return AppTTS.speak(text, { voice: 'af_bella', speed });
    }
  }

  function cancel() {
    _cancelId++;
    if (_currentSource) {
      try { _currentSource.stop(); } catch (_) {}
      _currentSource = null;
    }
    if (typeof AppTTS !== 'undefined') AppTTS.cancel();
  }

  /**
   * Pre-warm AudioContext on first interaction.
   * Also warms up AppTTS so Kokoro is ready if fallback is needed.
   */
  function warmup() {
    // Don't pre-create the Kokoro worker — it's a fallback only, created on demand.
    document.addEventListener('pointerdown', () => {
      _getCtx().resume().catch(() => {});
    }, { once: true });
  }

  return { play, cancel, warmup, setBase, voices: VOICES };
})();
