/* ============================================================
   progress.js — SM-2 Spaced Repetition Engine
   Based on SM-2 (Wozniak 1990) with two intentional divergences:
     1. EF ceiling raised from 2.5 → 3.0
     2. Easy bonus multiplier of ×1.3 on interval

   Storage key: pe_progress  (auto-migrated from pe_srs on first load)
   Card format: { interval, ease, reps, lapses, due }
     interval — days until next review
     ease     — ease factor (SM-2)
     reps     — total correct-or-attempted reviews
     lapses   — number of Hard answers
     due      — timestamp (ms) when next review is due

   Visual mastery states (derived, never stored):
     new       → reps === 0
     learning  → interval ≤ 3
     practiced → interval 4–14
     mastered  → interval > 14
   ============================================================ */

const Progress = (() => {
  const STORE_KEY      = AppLangPair.storageKey('pe_progress');
  const LEGACY_KEY     = 'pe_srs';
  const SCHEMA_VERSION = 3;   // v3: positional cardIds → stable string IDs

  // ── SM-2 algorithm parameters ─────────────────────────────────────────
  const EF_DEFAULT      = 2.5;
  const EF_MIN          = 1.3;
  const EF_MAX          = 3.0;
  const EF_HARD_PENALTY = 0.2;
  const EF_OK_PENALTY   = 0.14;
  const EF_EASY_BOOST   = 0.1;
  const EF_EASY_BONUS   = 1.3;

  // ── Migration from pe_srs (old key) ───────────────────────────────────

  function _migrateLegacy() {
    try {
      const raw = localStorage.getItem(LEGACY_KEY);
      if (!raw) return null;
      const old = JSON.parse(raw);
      if (!old || typeof old !== 'object') return null;

      const data = { _v: SCHEMA_VERSION, cards: {} };
      if (old._sessions) data._sessions = old._sessions;
      if (old._streak)   data._streak   = old._streak;

      // Convert each SM-2 card — structure is identical, just add due=0 (immediately due)
      Object.keys(old).forEach(key => {
        if (key.startsWith('_')) return;
        const v = old[key];
        if (!v || typeof v !== 'object') return;
        const reps     = typeof v.reps     === 'number' ? v.reps     : 0;
        const interval = typeof v.interval === 'number' ? v.interval : 0;
        const ease     = typeof v.ease     === 'number' ? v.ease     : EF_DEFAULT;
        const lapses   = typeof v.lapses   === 'number' ? v.lapses   : 0;
        data.cards[key] = { interval, ease, reps, lapses, due: 0 };
      });

      // Carry over placement level
      const level = localStorage.getItem(AppLangPair.storageKey('pe_placement_level'));
      if (level) data.level = level;

      localStorage.setItem(STORE_KEY, JSON.stringify(data));
      localStorage.removeItem(LEGACY_KEY);
      return data;
    } catch (e) {
      return null;
    }
  }

  // ── Migration v2→v3: positional cardIds → stable string IDs ────────────
  // Compact lookup table: topic → [phraseId at origIdx 0, 1, 2, …]
  // Generated by tools/migrate-stable-ids.mjs — do not edit by hand.
  const _ID_MAP = {"phrases":{"greetings":["greetings_hello_how_are_you_today","greetings_good_morning_its_nice_to_see","greetings_hi_there_hows_your_day_going","greetings_good_afternoon_how_have_you_been","greetings_hey_hows_everything_with_you","greetings_morning_hope_youre_doing_well","greetings_good_evening_hows_your_day_been","greetings_hey_hows_life_treating_you","greetings_hi_its_good_to_catch_up","greetings_hello_how_have_you_been_lately","greetings_hi_there_hope_youre_having_a","greetings_hey_whats_new_with_you","greetings_good_morning_hows_everything_going","greetings_hi_how_are_you_holding_up","greetings_hey_there_hows_your_week_been","greetings_hello_hope_youre_doing_fine","greetings_hi_its_been_a_while_how","greetings_good_afternoon_hows_life_treating_you","greetings_hey_nice_to_see_you_again","greetings_it_was_great_seeing_you","greetings_take_care_of_yourself","greetings_have_a_wonderful_day","greetings_see_you_around","greetings_it_was_lovely_to_meet_you","greetings_dont_be_a_stranger","greetings_we_should_do_this_again_sometime","greetings_it_was_a_pleasure_hope_to","greetings_say_hi_to_everyone_for_me","greetings_take_care_and_stay_in_touch","greetings_it_was_so_good_catching_up","greetings_nice_to_meet_you_im_glad","greetings_i_could_be_better","greetings_hows_your_day_been","greetings_ive_had_a_great_day","greetings_hows_your_week_been","greetings_ive_had_better_days","greetings_im_sad","greetings_im_happy","greetings_im_excited","greetings_im_bored","greetings_im_tired","greetings_im_angry","greetings_im_surprised","greetings_im_confused","greetings_im_worried","greetings_im_nervous","greetings_im_scared","greetings_im_relaxed","greetings_im_stressed","greetings_im_busy","greetings_why_are_you_sad","greetings_why_are_you_so_happy","greetings_why_are_you_excited","greetings_why_are_you_bored","greetings_why_are_you_tired","greetings_why_are_you_angry","greetings_why_are_you_surprised","greetings_why_are_you_confused","greetings_why_are_you_worried","greetings_why_are_you_nervous","greetings_why_are_you_scared","greetings_why_are_you_relaxed","greetings_why_are_you_stressed","greetings_whats_on_your_mind","greetings_is_there_anything_i_can_do","greetings_introduce_myself_account_manager","greetings_pleasure_meeting_follow_up","greetings_allow_me_to_introduce_dr","greetings_sincere_condolences_loss","greetings_welcome_aboard_team","greetings_trust_message_finds_you_well","greetings_pleasure_introduce_keynote_speaker","greetings_dont_believe_formally_introduced","greetings_convey_delegation_graciously_received","greetings_appreciate_time_demanding_schedule","greetings_honor_welcome_distinguished_delegates","greetings_cultural_awareness_not_merely_etiquette","greetings_protocol_introductions_senior_first","greetings_remiss_not_acknowledge_contribution","greetings_sincere_felicitations_promotion"],"restaurant":["restaurant_can_we_see_the_menu_please","restaurant_do_you_have_any_vegetarian_options","restaurant_what_do_you_recommend_as_a","restaurant_could_you_tell_me_about_todays","restaurant_is_this_dish_spicy","restaurant_could_i_have_this_dish_without","restaurant_do_you_offer_glutenfree_alternatives","restaurant_how_long_will_the_food_take","restaurant_could_i_have_a_glass_of","restaurant_is_it_possible_to_split_the","restaurant_do_you_have_any_desserts_available","restaurant_could_i_have_some_extra_napkins","restaurant_is_the_tip_included_in_the","restaurant_can_i_get_a_refill_on","restaurant_do_you_have_any_recommendations_for","restaurant_do_you_offer_any_childrens_menus","restaurant_could_i_have_some_bread_while","restaurant_is_there_a_minimum_order_for","restaurant_can_i_make_a_reservation_for","restaurant_could_i_have_some_more_ice","restaurant_do_you_offer_any_discounts_for","restaurant_is_there_a_corkage_fee_if","restaurant_could_i_have_my_steak_cooked","restaurant_is_there_a_limit_to_the","restaurant_do_you_have_any_recommendations_for_2","restaurant_could_i_have_some_extra_sauce","restaurant_is_it_possible_to_have_my","restaurant_could_you_recommend_a_good_wine","restaurant_do_you_have_any_outdoor_seating","restaurant_could_i_have_the_bill_please","restaurant_is_there_a_happy_hour_special","restaurant_do_you_offer_any_lowcalorie_options","restaurant_could_you_help_me_pronounce_this","restaurant_is_there_a_time_limit_for","restaurant_do_you_have_any_options_for","restaurant_could_i_have_my_coffee_with","restaurant_is_there_a_dress_code_for","restaurant_do_you_have_any_recommendations_for_3","restaurant_could_i_have_the_check_split","restaurant_is_there_a_charge_for_substitutions","restaurant_do_you_offer_any_birthday_specials","restaurant_could_i_order_a_side_of","restaurant_is_there_a_fee_for_using","restaurant_do_you_have_a_dogfriendly_patio","restaurant_could_i_have_my_burger_cooked","restaurant_is_there_a_childrens_menu_available","restaurant_could_you_please_pack_the_leftovers","restaurant_do_you_have_any_nonalcoholic_cocktails","restaurant_could_i_have_my_salad_with","restaurant_is_there_a_service_charge_for","restaurant_could_you_recommend_a_dish_for","restaurant_do_you_have_any_specials_for","restaurant_could_you_turn_down_the_music","restaurant_is_it_possible_to_make_a","restaurant_could_i_have_some_extra_cheese","restaurant_allergy_chef_ingredients","restaurant_steak_wrong_doneness","restaurant_wine_wrong_selection","restaurant_compliment_chef_risotto","restaurant_same_table_window","restaurant_tasting_menu_chef_selections","restaurant_wine_acidity_fish_pairing","restaurant_personalized_dessert_occasion","restaurant_price_discrepancy_charged","restaurant_private_dining_business","restaurant_amuse_bouche_ambition_restraint","restaurant_wine_pairing_burgundy_premature","restaurant_tasting_menu_progression_redundancy","restaurant_sommelier_provenance_barolo","restaurant_attentiveness_discretion_equilibrium"],"supermarket":["supermarket_have_you_made_the_grocery_list","supermarket_i_need_to_buy_milk_bread","supermarket_dont_forget_to_buy_fruits_and","supermarket_this_supermarket_is_very_expensive_lets","supermarket_there_is_an_offer_on_the","supermarket_can_you_help_me_carry_the","supermarket_i_dont_have_cash_can_i","supermarket_where_are_the_cookies","supermarket_i_cant_find_the_yogurt_brand","supermarket_how_much_does_a_kilo_of","supermarket_where_is_the_cleaning_products_section","supermarket_i_need_to_buy_a_new","supermarket_is_this_product_vegan","supermarket_do_you_know_which_pasta_brand","supermarket_is_there_any_offer_on_cereals","supermarket_there_is_a_long_line_at","supermarket_can_you_help_me_reach_that","supermarket_i_cant_find_an_employee_to","supermarket_what_time_does_the_supermarket_close","supermarket_where_are_the_shopping_carts","supermarket_is_there_a_bathroom_nearby","supermarket_this_supermarket_has_a_very_useful","supermarket_i_received_a_discount_coupon_in","supermarket_i_like_to_use_the_selfservice","supermarket_i_dont_like_this_supermarket_its","supermarket_i_prefer_to_go_to_the","supermarket_you_have_to_go_to_the","supermarket_i_will_need_a_purchase_ticket","supermarket_are_these_grapes_organic","supermarket_do_you_have_fresh_chicken","supermarket_i_dont_know_which_fish_to","supermarket_the_strawberries_are_very_expensive","supermarket_im_looking_for_a_cake_for","supermarket_can_you_give_me_the_receipt","supermarket_where_is_the_glutenfree_products_section","supermarket_do_you_have_almond_milk","supermarket_where_is_the_personal_hygiene_products","supermarket_where_is_the_cleaning_products_section_2","supermarket_where_is_the_bakery_section","supermarket_can_you_give_me_a_bag","supermarket_i_am_here_to_make_a","supermarket_i_dont_like_this_supermarket_the","supermarket_i_didnt_find_the_product_i","supermarket_do_you_have_larger_size","supermarket_store_brand_less_expensive","supermarket_speak_to_manager_mislabeled","supermarket_where_are_gluten_free_products","supermarket_shelf_price_doesnt_match_register","supermarket_nut_allergy_processed_facility","supermarket_return_seal_broken_spoiled","supermarket_check_stockroom_out_of_shelf","supermarket_overcharged_promotional_price_not_applied","supermarket_customer_service_lodge_complaint","supermarket_deli_cross_contamination_intolerance","supermarket_best_before_use_by_mislead","supermarket_sourcing_policy_free_range_certification","supermarket_escalate_staff_assurance_not_honored","supermarket_online_listing_out_of_stock_delivery","supermarket_fair_trade_certifications_suppliers","supermarket_cold_chain_thaw_refreeze_food_safety","supermarket_traceability_protocols_supply_chain","supermarket_sustainability_report_food_waste_measures","supermarket_food_safety_inspector_temperature_logs"],"kitchen":["kitchen_do_we_have_enough_eggs_for","kitchen_pass_me_the_cutting_board","kitchen_where_do_we_keep_the_measuring","kitchen_can_you_pass_me_the_spatula","kitchen_do_we_have_any_olive_oil","kitchen_pass_me_the_salt_from_the","kitchen_we_need_to_replace_the_baking","kitchen_the_mixer_is_in_the_cabinet","kitchen_the_baking_sheets_are_on_the","kitchen_do_we_have_any_fresh_herbs","kitchen_can_you_check_if_the_oven","kitchen_baking_soda_will_help_the_dough","kitchen_do_we_have_parchment_paper_to","kitchen_help_me_peel_the_carrots_and","kitchen_we_need_to_wash_the_cheese","kitchen_do_we_have_vanilla_extract_for","kitchen_could_you_rinse_the_vegetables_with","kitchen_the_knives_need_sharpening","kitchen_we_need_to_take_the_meat","kitchen_the_spices_and_condiments_are_in","kitchen_do_we_have_aluminum_foil_to","kitchen_we_need_to_finely_chop_the","kitchen_can_you_pass_me_the_colander","kitchen_we_need_to_buy_unsalted_butter","kitchen_could_you_help_me_open_this","kitchen_the_recipe_calls_for_brown_sugar","kitchen_the_rolling_pin_to_flatten_the","kitchen_whats_the_difference_between_a_pot","kitchen_do_we_have_breadcrumbs_to_coat","kitchen_where_do_we_keep_the_plastic","kitchen_the_milk_has_curdled","kitchen_this_sauce_has_expired","kitchen_we_dont_have_the_necessary_ingredients","kitchen_reducing_the_sauce_will_take_time","kitchen_marinade_is_a_commonly_used_seasoning","kitchen_the_salad_will_need_oil_vinegar","kitchen_could_you_help_me_sift_the","kitchen_put_the_leftovers_in_plastic_containers","kitchen_theres_leftover_broth_for_the_soup","kitchen_be_careful_with_the_hot_pot","kitchen_the_soup_needs_more_salt","kitchen_have_you_already_cut_the_vegetables","kitchen_add_a_little_sugar_to_the","kitchen_we_need_to_preheat_the_oven","kitchen_take_the_food_out_of_the","kitchen_tonight_were_making_homemade_pizza","kitchen_im_going_to_make_chicken_and","kitchen_i_need_a_tablespoon_of_butter","kitchen_could_you_chop_the_vegetables_into","kitchen_the_pan_is_too_hot_lower","kitchen_where_are_the_clean_dishes","kitchen_wash_the_fruit_before_cutting_it","kitchen_to_make_flan_you_have_to","kitchen_to_make_flan_you_have_to_2","kitchen_to_cook_chicken_better_you_have","kitchen_let_the_pizza_dough_rest_before","kitchen_season_the_chicken_with_salt_pepper","kitchen_while_i_remove_the_fish_bones","kitchen_the_stove_doesnt_seem_to_be","kitchen_we_need_to_skim_the_broth","kitchen_bread_the_fish_with_breadcrumbs_and","kitchen_the_sauce_needs_more_salt","kitchen_peel_the_potatoes_and_then_slice","kitchen_steam_the_vegetables","kitchen_grill_the_meat","kitchen_boil_the_pasta_in_hot_water","kitchen_fry_the_potatoes_in_hot_oil","kitchen_we_need_to_broil_the_cheese","kitchen_the_best_side_dish_for_fish","kitchen_the_best_side_dish_for_meat","kitchen_the_best_side_dish_for_pasta","kitchen_the_best_side_dish_for_chicken","kitchen_before_cooking_pasta_we_have_to","kitchen_dry_the_sink_after_washing_the","kitchen_lower_the_temperature_of_the_freezer","kitchen_i_prefer_to_use_the_electric","kitchen_the_glasses_are_hanging_on_the","kitchen_the_blender_is_in_the_cabinet","kitchen_the_mixer_is_in_the_drawer","kitchen_the_coffee_maker_is_on_the","kitchen_the_toaster_is_on_the_table","kitchen_the_sandwich_maker_is_in_the","kitchen_the_pot_is_on_the_stove","kitchen_the_pan_is_in_the_sink","kitchen_the_casserole_dish_is_in_the","kitchen_the_grill_is_on_the_patio","kitchen_the_forks_and_knives_are_in","kitchen_we_need_to_wash_the_spoons","kitchen_the_cutting_board_is_in_the","kitchen_the_glasses_and_cups_are_in","kitchen_the_fruit_bowl_is_on_the","kitchen_deglaze_pan_white_wine","kitchen_fold_egg_whites_not_stir","kitchen_let_meat_rest_juices_redistribute","kitchen_blanch_vegetables_before_stir_fry","kitchen_score_duck_skin_fat_renders","kitchen_emulsified_vinaigrette_add_oil_slowly","kitchen_sauce_breaks_rescue_cold_water","kitchen_brine_chicken_overnight_juicier","kitchen_caramelized_onions_deglaze_balsamic","kitchen_make_day_ahead_flavors_meld","kitchen_spherification_gel_membrane","kitchen_tempered_chocolate_crystalline_snap","kitchen_sous_vide_precise_temperature_control","kitchen_fat_flour_ratio_structural_integrity","kitchen_maillard_reaction_browning_flavor"],"transportation":["transportation_order_taxi_morning","transportation_where_taxi_stand","transportation_how_get_bus_stop","transportation_nearest_bus_stop","transportation_where_rent_bike","transportation_boat_arrive_port","transportation_rental_car_location","transportation_buy_train_ticket","transportation_taxi_fare_city","transportation_payment_airport_transfer","transportation_metro_faster_than_bus","transportation_subway_single_fare","transportation_weekly_travel_pass","transportation_bus_late_connection","transportation_call_cab_station","transportation_missed_train_next_one","transportation_metro_map_navigate","transportation_driver_overcharged_complaint","transportation_reduced_fare_students","transportation_bike_brakes_faulty","transportation_rideshare_late_arrival","transportation_monthly_multimodal_pass","transportation_taxi_longer_route_fare","transportation_cycling_lane_shared_road","transportation_cancelled_train_refund","transportation_accessible_wheelchair_vehicle","transportation_congestion_pricing_city_center","transportation_rental_liability_provisions","transportation_taxi_deregulation_standards","transportation_intermodal_urban_emissions","transportation_penalty_charge_signage"],"airport":["airport_flight_departure_time","airport_check_luggage","airport_waiting_room_location","airport_prefer_window_seat","airport_boarding_pass_gate","airport_carryon_size_limit","airport_exchange_currency","airport_which_terminal_departs","airport_how_early_arrive","airport_direct_or_connecting","airport_flight_delayed_voucher","airport_request_seat_front","airport_carryon_over_limit","airport_baggage_claim_flight","airport_connection_time_enough","airport_luggage_lost_claim","airport_denied_boarding_compensation","airport_immigration_before_bags","airport_seat_changed_no_notice","airport_bag_made_connection","airport_customs_declare_allowance","airport_passport_expiry_visa","airport_transit_zone_restrictions","airport_upgrade_miles_business","airport_mishandled_bag_return","airport_eu_regulation_compensation","airport_secondary_screening_rights","airport_partner_airline_baggage_liability","airport_force_majeure_rebook","airport_asylum_request_procedure"],"accommodation":["accommodation_breakfast_included","accommodation_extra_towels","accommodation_hotel_services","accommodation_minibar_room","accommodation_recommend_restaurant","accommodation_wifi_password","accommodation_gym_hotel","accommodation_help_luggage","accommodation_safe_room","accommodation_extra_pillow","accommodation_restaurant_closing","accommodation_atm_hotel","accommodation_pool_hotel","accommodation_checkin_time","accommodation_checkout_time","accommodation_closest_restaurant","accommodation_drinks_included","accommodation_book_room_two_nights","accommodation_single_room_availability","accommodation_confirm_reservation","accommodation_do_not_disturb","accommodation_airport_shuttle","accommodation_nonsmoking_room","accommodation_room_service_24h","accommodation_guest_access","accommodation_store_luggage","accommodation_spa_service","accommodation_transport_options","accommodation_room_sea_view","accommodation_late_checkout_policy","accommodation_cancellation_policy","accommodation_pet_policy","accommodation_early_checkin_policy","accommodation_refund_policy","accommodation_power_adapters","accommodation_extend_stay_price","accommodation_room_not_cleaned_discount","accommodation_unexplained_charge_bill","accommodation_early_checkin_early_flight","accommodation_aircon_maintenance","accommodation_extend_stay_same_rate","accommodation_corporate_rate_booking","accommodation_room_doesnt_match_manager","accommodation_formal_complaint_noise","accommodation_itemize_bill_expense","accommodation_retrieve_valuables_safe","accommodation_force_majeure_cancellation","accommodation_room_misrepresented_listing","accommodation_longstay_discount_negotiation","accommodation_damages_assessment_criteria","accommodation_loyalty_tier_benefits"],"movies":["movies_bad_ending","movies_go_cinema_weekend","movies_good_actor","movies_watching_netflix_series","movies_good_movie_recommend","movies_seen_horror_movie","movies_looking_new_series","movies_classic_movie","movies_new_director_movie","movies_disappointed_last_season","movies_seen_latest_episode","movies_dont_understand_popularity","movies_series_recommendation","movies_seen_new_trailer","movies_prefer_cinema_home","movies_film_festival_city","movies_what_time_starts","movies_documentary_streaming","movies_special_effects_incredible","movies_binge_watching_cant_stop","movies_midnight_premiere_sells_out","movies_prefer_thrillers_not_action","movies_unexpected_twist_ending","movies_second_half_pacing_rushed","movies_book_adaptation_missing_scenes","movies_previous_film_more_compelling","movies_oscars_best_picture_overhyped","movies_themes_identity_narrative","movies_nonlinear_storytelling_effective","movies_performances_script_characters","movies_unflinching_poverty_sentimentality","movies_cinematography_worth_watching","movies_deconstruct_genre_vigilante","movies_subverts_conventions_critical_acclaim","movies_auteur_long_takes_body_of_work","movies_polemic_consumerism_commercial","movies_refuses_easy_moral_resolution"],"music":["music_skip_song","music_favorite_song_always","music_favorite_song","music_go_concert_year","music_new_concert_band","music_podcasts_while_exercise","music_podcast_recommendation","music_song_special_memory","music_new_album_disappointment","music_what_kind_do_you_like","music_love_this_song_who_sings","music_add_song_playlist","music_learning_guitar_six_months","music_opening_act_surprised","music_headphones_or_speakers","music_live_better_than_studio","music_similar_genre_film","music_vocal_range_earlier_work","music_festival_lineup_disappointing","music_classical_pianist_switched_jazz","music_lyrics_political_commentary","music_blends_traditional_contemporary","music_indie_influence_underestimated","music_chord_progression_unsettling","music_reinterprets_makes_her_own","music_departure_genre_conventions","music_african_polyrhythms_western_harmony","music_meditation_collective_memory","music_instrumentation_mirrors_lyrics","music_folk_motifs_authenticity"],"theater":["theater_art_exhibition_invite","theater_photography_exhibition","theater_moving_play","theater_visit_new_museum","theater_opera_surprised","theater_buy_tickets_tonight","theater_where_is_theater","theater_what_time_performance","theater_enjoy_going_theater","theater_actors_incredible_performance","theater_tickets_saturday","theater_intermission_refreshments","theater_moved_by_grief_portrayal","theater_contemporary_art_museum","theater_arrive_early_installation","theater_staging_final_scene","theater_museum_retrospective_evolution","theater_script_overambitious_themes","theater_physical_performance_no_dialogue","theater_set_design_bleak_story","theater_subverts_expectations_first_scene","theater_exhibition_cultural_ownership","theater_playwright_social_critique_domestic","theater_lighting_sound_immersive","theater_ambiguous_ending_interpretations","theater_psychological_disintegration_tour_de_force","theater_installation_commodification_audience","theater_classical_text_contemporary_aesthetics","theater_brechtian_alienation_identification","theater_curatorial_thesis_uneven_works"],"gym":["gym_can_you_show_me_how_to","gym_what_is_the_correct_form_for","gym_increase_the_elevation_of_the_treadmill","gym_increase_the_speed_of_the_treadmill","gym_how_many_repetitions_should_i_do","gym_could_you_demonstrate_how_to_do","gym_can_you_recommend_an_appropriate_weight","gym_is_there_a_warmup_i_should","gym_how_do_i_adjust_the_seat","gym_can_you_give_me_some_tips","gym_what_exercises_do_you_recommend_for","gym_could_you_tell_me_if_im","gym_today_is_leg_day","gym_tomorrow_will_be_arm_day","gym_is_it_okay_if_i_work","gym_could_you_explain_the_benefits_of","gym_what_is_the_proper_breathing_technique","gym_do_you_have_any_suggestions_for","gym_should_i_follow_any_kind_of","gym_we_all_must_properly_disinfect_the","gym_could_you_recommend_a_stretching_routine","gym_do_you_have_any_advice_for","gym_can_you_show_me_how_to_2","gym_what_routine_should_i_follow","gym_what_is_the_best_way_to","gym_how_much_cardio_time_do_i","gym_is_there_a_specific_order_i","gym_what_is_the_correct_posture_for","gym_how_much_rest_time_do_you","gym_do_you_have_any_tips_for","gym_could_you_demonstrate_how_to_use","gym_is_it_okay_if_i_use","gym_im_going_to_do_cardio_and","gym_i_dont_know_how_to_use","gym_where_can_i_find_towels","gym_could_you_help_me_create_a","gym_what_type_of_membership_do_you","gym_is_there_a_personal_trainer_available","gym_are_group_classes_available","gym_how_can_i_book_a_class","gym_what_is_the_gyms_schedule","gym_what_muscles_are_worked_with_this","gym_i_feel_a_pain_in_my","gym_the_gyms_music_is_too_loud","gym_im_motivated","gym_could_you_inform_me_about_the","gym_that_effort_was_worth_it","gym_is_there_an_alternative_for_that","gym_i_need_to_work_on_my","gym_i_need_to_rest_a_bit","gym_how_long_should_i_rest_between","gym_i_would_like_to_work_on","gym_this_exercise_will_help_me_strengthen","gym_this_routine_is_designed_to_work","gym_keep_your_back_straight","gym_breathe_deeply","gym_push_with_your_heels_not_with","gym_keep_your_elbows_close_to_your","gym_dont_lift_your_shoulders_towards_your","gym_keep_your_abs_contracted","gym_dont_arch_your_back","gym_maintain_a_steady_pace","gym_breathe_deeply_and_through_your_nose","gym_dont_forget_to_hydrate","gym_eat_healthily_to_get_better_results","gym_rest_enough_for_your_body_to","gym_dont_overdo_it_with_the_weight","gym_they_are_cleaning_the_locker_rooms","gym_shoulder_discomfort_overhead_press","gym_cable_machine_seated_row","gym_progress_plateaued_modify_program","gym_hiit_cardiovascular_endurance","gym_knee_injury_high_impact_avoid","gym_periodization_hypertrophy_strength","gym_macronutrients_protein_training_load","gym_strength_imbalance_dominant_side","gym_overtraining_recovery_as_important","gym_progressive_overload_adaptations","gym_concurrent_training_interference_strength","gym_blood_flow_restriction_rehabilitation","gym_specificity_training_adaptations","gym_myofascial_release_motor_recruitment","gym_squat_hip_hinge_biomechanics"],"technology":["technology_could_you_send_me_that_document","technology_i_need_to_charge_my_phone","technology_can_you_help_me_set_up","technology_what_is_the_wifi_password","technology_wait_my_computer_is_updating","technology_tomorrow_we_are_going_to_have","technology_do_you_know_how_i_can","technology_can_you_copy_me_on_that","technology_send_me_that_file_via_whatsapp","technology_can_you_share_your_location","technology_i_need_to_back_up_my","technology_is_there_a_way_to_block","technology_how_do_i_delete_this_app","technology_i_forgot_my_password","technology_is_there_an_app_to_scan","technology_do_you_have_a_cable_you","technology_how_do_i_save_this_file","technology_i_want_to_buy_a_camera","technology_can_i_turn_off_notifications_for","technology_how_do_i_take_a_screenshot","technology_make_sure_your_internet_connection_is","technology_i_recommend_using_a_strong_and","technology_can_i_connect_the_speaker_to","technology_i_suggest_you_use_a_vpn","technology_where_is_the_tv_remote_control","technology_we_need_to_buy_more_ink","technology_i_really_liked_this_image_im","technology_have_you_seen_my_message_in","technology_check_your_spam_the_email_might","technology_do_you_have_coverage_in_this","technology_the_battery_of_my_smartwatch_doesnt","technology_i_cant_connect_my_device_to","technology_i_need_a_new_usb_cable","technology_the_wifi_is_not_working_can","technology_be_careful_with_that_link_it","technology_the_app_works_better_than_the","technology_lets_look_for_an_internet_tutorial","technology_what_cell_phone_do_you_recommend","technology_scan_this_qr_code_for_more","technology_i_cant_open_this_file_what","technology_i_need_to_download_this_program","technology_how_can_i_recover_a_deleted","technology_you_should_look_it_up_on","technology_i_accidentally_deleted_the_conversation_can","technology_dont_trust_all_the_information_you","technology_do_you_know_how_to_use","technology_i_cant_open_this_pdf_file","technology_im_looking_for_software_to_record","technology_what_is_this_formula_in_excel","technology_this_powerpoint_presentation_is_very_boring","technology_the_information_is_in_the_attached","technology_i_want_to_increase_the_brightness","technology_turn_on_the_scanner_i_need","technology_you_should_buy_a_better_mouse","technology_these_wireless_headphones_are_very_comfortable","technology_the_virtual_assistant_has_been_failing","technology_the_battery_of_this_phone_could","technology_i_love_the_camera_on_this","technology_how_can_i_change_the_language","technology_i_dont_know_where_the_portable","technology_look_for_the_file_in_the","technology_are_you_sure_you_are_connected","technology_please_turn_on_the_printer","technology_how_do_you_do_this_in","technology_my_phone_keeps_overheating_when","technology_the_new_operating_system_update","technology_i_enabled_twofactor_authentication_on","technology_the_streaming_quality_drops_when","technology_i_set_up_automatic_cloud_backups","technology_my_privacy_settings_dont_seem","technology_i_received_a_phishing_email","technology_clearing_the_cache_usually_fixes","technology_the_devices_firmware_needs_to","technology_im_considering_switching_ecosystems_but","technology_the_company_acknowledged_a_data","technology_planned_obsolescence_means_manufacturers_intentionally","technology_endtoend_encryption_ensures_that_not","technology_cybersecurity_experts_recommend_using_a","technology_the_legacy_system_is_no_longer"],"accountability":["accountability_lets_start_the_meeting","accountability_the_financial_reports_have_been_reviewed","accountability_we_need_to_adjust_the_budget","accountability_the_sales_figures_have_increased","accountability_we_are_facing_a_cash_flow","accountability_we_need_to_audit_the_accounts","accountability_the_tax_returns_are_pending","accountability_the_inventory_needs_to_be_updated","accountability_we_have_a_new_client","accountability_we_are_closing_the_fiscal_year","accountability_we_need_to_reconcile_the_bank","accountability_the_payroll_is_paid","accountability_the_balance_sheet_is_ready","accountability_the_financial_statements_are_up_to","accountability_accounting_staff_will_be_here_tomorrow","accountability_the_accountant_needs_additional_information","accountability_everything_went_well_during_the_tax","accountability_the_financial_forecast_is_positive","accountability_have_the_contracts_with_the_suppliers","accountability_when_is_the_meeting_scheduled","accountability_it_is_important_to_consider_the","accountability_when_was_the_budget_review_scheduled","accountability_what_are_the_projections_for_the","accountability_the_sales_projection_for_the_next","accountability_accounts_payable_has_already_closed_its","accountability_the_accounting_department_has_already_delivered","accountability_the_human_resources_department_has_already","accountability_accounting_records_for_the_tax_return","accountability_the_presentation_of_the_financial_reports","accountability_all_the_money_a_person_receives","accountability_salary_is_paid_in_cash_check","accountability_salary_is_paid_weekly_biweekly_or","accountability_the_purchasing_department_will_receive_a","accountability_has_the_intern_already_registered_with","accountability_the_balance_sheet_shows_the_assets","accountability_i_think_this_is_a_good","accountability_the_company_had_higher_sales_and","accountability_if_the_company_buys_new_assets","accountability_the_inventory_that_arrived_yesterday_is","accountability_what_was_the_net_profit_from","accountability_what_was_the_gross_loss_from","accountability_a_companys_fiscal_year_does_not","accountability_the_companys_income_in_the_past","accountability_the_variance_between_projected_and","accountability_we_should_hedge_our_foreign","accountability_the_audit_committee_has_raised","accountability_depreciation_must_be_calculated_using","accountability_the_accounts_receivable_turnover_ratio","accountability_the_consolidated_financial_statements_reflect","accountability_revenue_recognition_must_comply_with","accountability_the_impairment_of_goodwill_has","accountability_any_contingent_liability_must_be","accountability_the_weighted_average_cost_of"]},"vocab":{"general":{"quizBase":"quiz_vocab","vocabBase":"vocab","ids":["abundant","accomplish","accurate","acquire","adapt","adequate","admire","advocate","ambitious","analyze","anxious","appropriate","assess","assume","benefit","broad","capable","challenge","clarify","collaborate","commit","complex","concise","confident","consistent","contribute","crucial","curious","debate","dedicate","demonstrate","determine","diverse","efficient","elaborate","emerge","emphasize","enormous","essential","establish","evaluate","evident","evolve","exceptional","explore","flexible","flourish","focus","fortunate","generate","genuine","grateful","highlight","humble","identify","implement","improve","indicate","inevitable","influence","innovative","inspire","interpret","investigate","logical","maintain","minimize","motivate","navigate","necessary","obvious","opportunity","overcome","passionate","persevere","persuade","potential","precise","prioritize","profound","realistic","recognize","relevant","remarkable","resilient","responsible","significant","strategy","struggle","sufficient","sustainable","transparent","unique","utilize","valuable","vast","versatile","vision","vulnerable","worthwhile","infer","nuance","articulate","scrutinize","cohesive","conviction","eloquent","reconcile","discern","paramount","analogous","circumvent","esoteric","preclude","cogent","disingenuous","inexorable","pragmatic","dichotomy","superfluous"]},"greetings":{"quizBase":"quiz_greetings","vocabBase":"vocab_greetings","ids":["introduction","casual","formal","farewell","compliment","pleasant","brief","acquaintance","sincerely","acknowledge","approachable","etiquette","cordial","pleasantry","reciprocate","rapport","salutation","protocol","preamble","demeanor","decorum","deference","propriety","felicitation","solemnity"]},"restaurant":{"quizBase":"quiz_restaurant","vocabBase":"vocab_restaurant","ids":["appetizer","reservation","menu","waiter","tip","bill","portion","cuisine","entr_e","dietary","seasoning","garnish","ambiance","sommelier","delicacy","pairing","palate","tasting_menu","accompaniment","corkage","terroir","umami","gastronomy","oenology","mouthfeel"]},"supermarket":{"quizBase":"quiz_supermarket","vocabBase":"vocab_supermarket","ids":["aisle","checkout","coupon","discount","receipt","cashier","expiration","organic","quantity","promotion","loyalty","bulk","generic","perishable","wholesale","allergen","traceability","markup","recall","supplier","procurement","cold_chain","shrinkage","supply_chain","adulteration"]},"kitchen":{"quizBase":"quiz_kitchen","vocabBase":"vocab_kitchen","ids":["recipe","ingredient","boil","blend","preheat","whisk","dice","marinate","grate","batter","utensil","simmer","saut","knead","broil","deglaze","emulsify","braise","render","blanch","spherification","temper","sous_vide","maillard","mise_en_place"]},"transportation":{"quizBase":"quiz_transportation","vocabBase":"vocab_transportation","ids":["bus","taxi","station","stop","metro","fare","route","transfer","schedule","itinerary","platform","timetable","carpool","commute","congestion","bypass","interchange","ridesharing","surcharge","infrastructure","accessibility","subsidy","penalty","liability","deregulation","congestion_pricing","intermodal","carbon_footprint","franchise"]},"airport":{"quizBase":"quiz_airport","vocabBase":"vocab_airport","ids":["flight","passport","gate","luggage","ticket","boarding","check_in","delay","currency","destination","customs","layover","transit","turbulence","jet_lag","immigration","baggage_claim","overbooked","upgrade","voucher","duty_free","biometrics","prohibited","carrier","overbooking","repatriation","asylum","contraband","manifest","force_majeure"]},"accommodation":{"quizBase":"quiz_accommodation","vocabBase":"vocab_accommodation","ids":["hotel","room","reservation","hostel","key","checkout","reception","balcony","parking","towel","accommodation","amenities","complimentary","suite","housekeeping","tariff","concierge","deposit","occupancy","refund","invoice","complaint","liability","waiver","corporate_rate","indemnify","misrepresentation","arbitration","discretion","remittance"]},"movies":{"quizBase":"quiz_movies","vocabBase":"vocab_movies","ids":["movie","actor","cinema","series","scene","streaming","trailer","plot","documentary","subscription","binge_watch","genre","sequel","soundtrack","premiere","cast","protagonist","acclaimed","dialogue","blockbuster","subplot","cinematography","narrative","pacing","screenplay","auteur","allegory","subtext","mise_en_scene","denouement","polemic"]},"music":{"quizBase":"quiz_music","vocabBase":"vocab_music","ids":["song","singer","concert","playlist","band","album","lyrics","instrument","beat","genre","chorus","melody","acoustic","tour","pitch","setlist","venue","remix","virtuoso","improvisation","dissonance","arrangement","timbre","counterpoint","polyrhythm","leitmotif","atonal","syncopation","appropriation"]},"theater":{"quizBase":"quiz_theater","vocabBase":"vocab_theater","ids":["theater","play","museum","exhibition","stage","performance","gallery","opera","audience","ticket","intermission","set","rehearsal","curtain_call","retrospective","nostalgia","staging","playwright","script","curator","mise_en_scene","dramaturgy","subversive","installation","catharsis","alienation_effect","commodification","repatriation","postmodern","provenance"]},"gym":{"quizBase":"quiz_gym","vocabBase":"vocab_gym","ids":["repetition","cardio","posture","routine","warm_up","stamina","flexibility","intensity","recovery","resistance","endurance","spotter","metabolism","plateau","overtraining","periodization","hypertrophy","progressive_overload","proprioception","deload","biomechanics","lactate_threshold","catabolism","vo2_max","myofascial_release"]},"technology":{"quizBase":"quiz_technology","vocabBase":"vocab_technology","ids":["device","software","password","browser","upload","download","wireless","notification","update","storage","compatible","bandwidth","encryption","algorithm","malware","latency","phishing","cache","vulnerability","ecosystem","data_breach","obsolescence","legacy","cybersecurity","proprietary"]},"accountability":{"quizBase":"quiz_accountability","vocabBase":"vocab_accountability","ids":["deadline","commitment","milestone","feedback","objective","priority","delegate","outcome","follow_up","accountable","transparent","initiative","procrastinate","benchmark","proactive","accountability_concept","discrepancy","compliance","variance","accrual","liability","fiduciary","amortization","solvency","contingency"]}}};

  const _PHRASE_ACTS = ['', 'dict_', 'cloze_', 'trans_', 'scramble_'];

  function _migrateCardIds(data) {
    if (!data || !data.cards) return data;
    const cards    = data.cards;
    const newCards = {};
    let   changed  = 0;

    Object.keys(cards).forEach(key => {
      if (key.startsWith('_') || key.startsWith('grammar_')) {
        newCards[key] = cards[key]; return;
      }

      // Try to match old positional phrase key: {actPrefix?}{topic}_{number}
      const phraseTopics = Object.keys(_ID_MAP.phrases);
      let mapped = false;

      for (const act of _PHRASE_ACTS) {
        for (const topic of phraseTopics) {
          const prefix = act + topic + '_';
          if (!key.startsWith(prefix)) continue;
          const rest = key.slice(prefix.length);
          if (!/^\d+$/.test(rest)) continue;  // not numeric → already new format
          const idx = parseInt(rest, 10);
          const ids = _ID_MAP.phrases[topic];
          if (idx >= ids.length) { newCards[key] = cards[key]; mapped = true; break; }
          const newKey = act + ids[idx];
          newCards[newKey] = cards[key];
          if (newKey !== key) changed++;
          mapped = true; break;
        }
        if (mapped) break;
      }

      if (!mapped) {
        // Try vocab key: {quizBase|vocabBase}_{number}
        const vocabEntries = Object.values(_ID_MAP.vocab);
        for (const entry of vocabEntries) {
          for (const base of [entry.quizBase, entry.vocabBase]) {
            const prefix = base + '_';
            if (!key.startsWith(prefix)) continue;
            const rest = key.slice(prefix.length);
            if (!/^\d+$/.test(rest)) continue;
            const idx = parseInt(rest, 10);
            if (idx >= entry.ids.length) { newCards[key] = cards[key]; mapped = true; break; }
            const newKey = base + '_' + entry.ids[idx];
            newCards[newKey] = cards[key];
            if (newKey !== key) changed++;
            mapped = true; break;
          }
          if (mapped) break;
        }
      }

      if (!mapped) newCards[key] = cards[key];
    });

    if (changed > 0) {
      data.cards = newCards;
      data._v = 3;
    }
    return data;
  }

  // ── Migration: traveling/entertainment → split topics ─────────────────
  // traveling and entertainment were split into more specific topics.
  // Old card IDs with those prefixes are orphaned — user re-learns with better scope.

  function _migrateSplitTopics(data) {
    if (!data || !data.cards || data._splitV >= 1) return false;
    const prefixes = ['traveling_', 'entertainment_'];
    const acts     = ['', 'dict_', 'cloze_', 'trans_', 'scramble_'];
    let   changed  = false;
    Object.keys(data.cards).forEach(id => {
      for (const act of acts) {
        for (const p of prefixes) {
          if (id === act + p.slice(0, -1) || id.startsWith(act + p)) {
            delete data.cards[id];
            changed = true;
          }
        }
      }
    });
    data._splitV = 1;
    return true; // always mark as done so we don't re-scan on every load
  }

  // ── Persistence ───────────────────────────────────────────────────────

  let _quotaWarned = false;

  function _showQuotaToast() {
    if (_quotaWarned) return;
    _quotaWarned = true;
    const t = document.createElement('div');
    t.setAttribute('role', 'alert');
    Object.assign(t.style, {
      position: 'fixed', bottom: '1.25rem', left: '50%', transform: 'translateX(-50%)',
      background: '#b91c1c', color: '#fff', borderRadius: '0.5rem',
      padding: '0.6rem 1.1rem', fontSize: '0.85rem', fontWeight: '600',
      zIndex: '10000', boxShadow: '0 4px 16px rgba(0,0,0,.25)',
      maxWidth: '90vw', textAlign: 'center',
    });
    t.textContent = AppLang.t('storage_full');
    document.body?.appendChild(t);
    setTimeout(() => t.remove(), 8000);
  }

  function _load() {
    try {
      const raw = localStorage.getItem(STORE_KEY);
      if (!raw) {
        const migrated = _migrateLegacy();
        if (migrated) return migrated;
        return { _v: SCHEMA_VERSION, cards: {} };
      }
      const data = JSON.parse(raw);
      if (!data || typeof data !== 'object') return { _v: SCHEMA_VERSION, cards: {} };
      if (!data.cards) data.cards = {};
      if (!data._v || data._v < 3) {
        const upgraded = _migrateCardIds(data);
        _migrateSplitTopics(upgraded);
        _save(upgraded);
        return upgraded;
      }
      if (_migrateSplitTopics(data)) _save(data);
      return data;
    } catch (e) {
      return { _v: SCHEMA_VERSION, cards: {} };
    }
  }

  function _save(data) {
    data._v = SCHEMA_VERSION;
    try { localStorage.setItem(STORE_KEY, JSON.stringify(data)); }
    catch (e) {
      if (e instanceof DOMException && (e.name === 'QuotaExceededError' || e.name === 'NS_ERROR_DOM_QUOTA_REACHED')) {
        _showQuotaToast();
      }
    }
  }

  // ── Card helpers ──────────────────────────────────────────────────────

  function _emptyCard() {
    return { interval: 0, ease: EF_DEFAULT, reps: 0, lapses: 0, due: 0 };
  }

  function getCard(id) {
    const data = _load();
    return data.cards[id] || _emptyCard();
  }

  // ── SM-2 rating ───────────────────────────────────────────────────────

  /**
   * Rate a card after review and advance its SM-2 schedule.
   * quality: 1 = Hard/wrong, 3 = OK/correct, 5 = Easy/correct
   */
  function rate(id, quality) {
    const data = _load();
    const card = data.cards[id] || _emptyCard();

    if (quality === 1) {
      card.interval = 1;
      card.ease     = Math.max(EF_MIN, card.ease - EF_HARD_PENALTY);
      card.lapses   = (card.lapses || 0) + 1;
      card.reps     = 0;
    } else if (quality === 3) {
      if (card.reps === 0)      card.interval = 1;
      else if (card.reps === 1) card.interval = 3;
      else                      card.interval = Math.max(1, Math.round(card.interval * card.ease));
      card.ease = Math.max(EF_MIN, card.ease - EF_OK_PENALTY);
    } else {
      if (card.reps === 0)      card.interval = 3;
      else if (card.reps === 1) card.interval = 5;
      else                      card.interval = Math.max(1, Math.round(card.interval * card.ease * EF_EASY_BONUS));
      card.ease = Math.min(EF_MAX, card.ease + EF_EASY_BOOST);
    }

    if (quality >= 3) card.lapses = Math.max(0, (card.lapses || 0) - 1);

    card.reps = (card.reps || 0) + 1;
    card.due  = Date.now() + card.interval * 86_400_000;

    data.cards[id] = card;
    _save(data);
  }

  // ── Visual mastery API ────────────────────────────────────────────────

  /**
   * Translate SM-2 interval → human-readable mastery state.
   * @param {string} id
   * @returns {'new'|'learning'|'practiced'|'mastered'}
   */
  function getMastery(id) {
    const card = getCard(id);
    if (card.reps === 0)       return 'new';
    if (card.interval <= 3)    return 'learning';
    if (card.interval <= 14)   return 'practiced';
    return 'mastered';
  }

  // ── Scheduling ────────────────────────────────────────────────────────

  /**
   * Return the index of the next card to review from cardIds.
   * Priority: due cards (due ≤ now) first, then new cards, then future cards.
   * @param {string[]} cardIds
   * @param {number}   excludeIdx — index to skip (just-reviewed card)
   * @returns {number}
   */
  function getNextIndex(cardIds, excludeIdx) {
    const data = _load();
    const now  = Date.now();
    let bestIdx   = -1;
    let bestScore = Infinity;

    for (let i = 0; i < cardIds.length; i++) {
      if (i === excludeIdx) continue;
      const card = data.cards[cardIds[i]];
      const reps = card ? card.reps : 0;
      const due  = card && card.due ? card.due : 0;

      // Score: 0 = due now (no card yet), 1 = overdue, 2+ = future
      // Within overdue: smaller interval = more urgent
      let score;
      if (reps === 0)      score = 50_000 + i;          // new: show after overdue, stable order
      else if (due <= now) score = card.interval;        // overdue: most urgent first
      else                 score = 100_000 + (due - now) / 86_400_000; // future: soonest first

      if (score < bestScore) { bestScore = score; bestIdx = i; }
    }

    return bestIdx === -1 ? 0 : bestIdx;
  }

  // ── Level ─────────────────────────────────────────────────────────────

  function setLevel(level) {
    const data = _load();
    data.level = level;
    _save(data);
    localStorage.setItem(AppLangPair.storageKey('pe_placement_level'), level);
  }

  function getLevel() {
    const data = _load();
    if (data.level) return data.level;
    return localStorage.getItem(AppLangPair.storageKey('pe_placement_level')) || 'A1';
  }

  // ── Sessions & streak ─────────────────────────────────────────────────

  function recordSession(topic, correct, total) {
    const data = _load();
    if (!data._sessions) data._sessions = [];
    data._sessions.push({
      date: new Date().toLocaleDateString('sv'),
      topic,
      correct,
      total
    });
    if (data._sessions.length > 100) data._sessions.shift();

    const today = new Date().toLocaleDateString('sv');
    const yd = new Date(); yd.setDate(yd.getDate() - 1);
    const yesterday = yd.toLocaleDateString('sv');
    if (!data._streak) data._streak = { current: 0, last: '', best: 0 };
    const s = data._streak;
    if (s.last !== today) {
      s.current = (s.last === yesterday) ? s.current + 1 : 1;
      s.last    = today;
      s.best    = Math.max(s.best, s.current);
    }
    _save(data);
  }

  function getStreak() {
    return _load()._streak || { current: 0, last: '', best: 0 };
  }

  function getSessions() {
    return _load()._sessions || [];
  }

  // ── getAllCards ────────────────────────────────────────────────────────

  /**
   * Returns all card data.
   * Exposes full SM-2 fields + aliases used by older callers:
   *   reps    — correct for all activity files and phrase-browser
   *   lapses  — used by grammar.js checks
   */
  function getAllCards() {
    const data = _load();
    const out  = {};

    if (data._sessions) out._sessions = data._sessions;
    if (data._streak)   out._streak   = data._streak;

    Object.keys(data.cards).forEach(key => {
      const v = data.cards[key];
      if (!v || typeof v !== 'object') return;
      out[key] = {
        interval: typeof v.interval === 'number' ? v.interval : 0,
        ease:     typeof v.ease     === 'number' ? v.ease     : EF_DEFAULT,
        reps:     typeof v.reps     === 'number' ? v.reps     : 0,
        lapses:   typeof v.lapses   === 'number' ? v.lapses   : 0,
        due:      typeof v.due      === 'number' ? v.due      : 0,
      };
    });

    return out;
  }

  // ── Stable-ID helpers (v3+) ──────────────────────────────────────────

  /**
   * Return the stable phraseIds for a topic (from the embedded ID map).
   * e.g. getPhraseIds('greetings') → ['greetings_hello_how_are_you_today', ...]
   */
  function getPhraseIds(topicId) {
    return (_ID_MAP.phrases[topicId] || []).slice();
  }

  /**
   * Return the stable wordIds for a vocab topic.
   * e.g. getVocabIds('general') → ['abundant', 'accomplish', ...]
   *      getVocabIds('greetings') → ['introduction', 'farewell', ...]
   */
  function getVocabIds(topicId) {
    const entry = _ID_MAP.vocab[topicId];
    return (entry && entry.ids) ? entry.ids.slice() : [];
  }

  /**
   * Count seen cards from an explicit list of card IDs.
   * 'seen' = reps ≥ 1.
   * @param {string[]} ids
   * @returns {{ seen: number, total: number }}
   */
  function getStatsForCards(ids) {
    const data = _load();
    const seen = ids.filter(id => { const c = data.cards[id]; return c && c.reps > 0; }).length;
    return { seen, total: ids.length };
  }

  return {
    getCard,
    rate,
    getMastery,
    getNextIndex,
    getPhraseIds,
    getVocabIds,
    getStatsForCards,
    setLevel,
    getLevel,
    recordSession,
    getStreak,
    getSessions,
    getAllCards,
  };
})();
