/* ============================================================
   progress.js — SM-2 Spaced Repetition Engine
   Based on SM-2 (Wozniak 1990) with two intentional divergences:
     1. EF ceiling raised from 2.5 → 3.0
     2. Easy bonus multiplier of ×1.3 on interval

   Storage key: pe_progress  (auto-migrated from pe_srs on first load)
   Card format: { interval, ease, reps, lapses, due }
     interval — days until next review
     ease     — ease factor (SM-2)
     reps     — total correct-or-attempted reviews
     lapses   — number of Hard answers
     due      — timestamp (ms) when next review is due

   Visual mastery states (derived, never stored):
     new       → reps === 0
     learning  → interval ≤ 3
     practiced → interval 4–14
     mastered  → interval > 14
   ============================================================ */

const Progress = (() => {
  const STORE_KEY      = AppLangPair.storageKey('pe_progress');
  const LEGACY_KEY     = 'pe_srs';
  const SCHEMA_VERSION = 3;   // v3: positional cardIds → stable string IDs

  // ── SM-2 algorithm parameters ─────────────────────────────────────────
  const EF_DEFAULT      = 2.5;
  const EF_MIN          = 1.3;
  const EF_MAX          = 3.0;
  const EF_HARD_PENALTY = 0.2;
  const EF_OK_PENALTY   = 0.14;
  const EF_EASY_BOOST   = 0.1;
  const EF_EASY_BONUS   = 1.3;

  // ── Migration from pe_srs (old key) ───────────────────────────────────

  function _migrateLegacy() {
    try {
      const raw = localStorage.getItem(LEGACY_KEY);
      if (!raw) return null;
      const old = JSON.parse(raw);
      if (!old || typeof old !== 'object') return null;

      const data = { _v: SCHEMA_VERSION, cards: {} };
      if (old._sessions) data._sessions = old._sessions;
      if (old._streak)   data._streak   = old._streak;

      // Convert each SM-2 card — structure is identical, just add due=0 (immediately due)
      Object.keys(old).forEach(key => {
        if (key.startsWith('_')) return;
        const v = old[key];
        if (!v || typeof v !== 'object') return;
        const reps     = typeof v.reps     === 'number' ? v.reps     : 0;
        const interval = typeof v.interval === 'number' ? v.interval : 0;
        const ease     = typeof v.ease     === 'number' ? v.ease     : EF_DEFAULT;
        const lapses   = typeof v.lapses   === 'number' ? v.lapses   : 0;
        data.cards[key] = { interval, ease, reps, lapses, due: 0 };
      });

      // Carry over placement level
      const level = localStorage.getItem(AppLangPair.storageKey('pe_placement_level'));
      if (level) data.level = level;

      localStorage.setItem(STORE_KEY, JSON.stringify(data));
      localStorage.removeItem(LEGACY_KEY);
      return data;
    } catch (e) {
      return null;
    }
  }

  // ── Migration v2→v3: positional cardIds → stable string IDs ────────────
  // Compact lookup table: topic → [phraseId at origIdx 0, 1, 2, …]
  // Maintained by tools/fix-phrase-ids.js — do not edit by hand.
  // Kept INLINE (not a fetched JSON) on purpose: progress.js is part of the offline
  // app shell (precached by the service worker), so inlining avoids an extra request
  // and works offline with no fallback logic. The size cost is an accepted trade-off;
  // if it grows large enough to matter, externalize it to a shell-precached JSON.
  // _ID_MAP is loaded lazily from shared/json/common/id-map.json (service-worker
  // precached, offline-safe) instead of being inlined here — inline it was ~70 KiB
  // parsed on the landing's critical path (gated first paint). Consumers read it via
  // _mapPhrases/_mapVocab (return {} until loaded); the v2→v3 card-id migration is
  // DEFERRED until it loads and NEVER bumps _v without a real remap (no progress loss).
  // Regenerated by tools/fix-phrase-ids.js.
  var _ID_MAP = null;
  var _idMapPromise = null;
  function _ensureIdMap() {
    if (_ID_MAP) return Promise.resolve(_ID_MAP);
    if (_idMapPromise) return _idMapPromise;
    var loader = (typeof AppData !== "undefined" && AppData.get)
      ? AppData.get("id-map")
      : fetch("shared/json/common/id-map.json").then(function (r) { return r.json(); });
    _idMapPromise = loader.then(function (m) {
      _ID_MAP = (m && m.phrases) ? m : { phrases: {}, vocab: {} };
      if (_cache && _cache.__pendingIdMigration) { _cache = null; _load(); }  // finish deferred v2→v3
      return _ID_MAP;
    }).catch(function () { _ID_MAP = { phrases: {}, vocab: {} }; return _ID_MAP; });
    return _idMapPromise;
  }
  function _mapPhrases(pair, esEnFallback) {
    if (!_ID_MAP) { _ensureIdMap(); return {}; }
    return _ID_MAP.phrases[pair] || (esEnFallback ? (_ID_MAP.phrases["es-en"] || {}) : {});
  }
  function _mapVocab(lang, enFallback) {
    if (!_ID_MAP) { _ensureIdMap(); return {}; }
    return _ID_MAP.vocab[lang] || (enFallback ? (_ID_MAP.vocab["en"] || {}) : {});
  }

  const _PHRASE_ACTS = ['', 'dict_', 'cloze_', 'trans_', 'scramble_'];

  // _ID_MAP.phrases is keyed by pair (phrase IDs are independent per pair).
  function _activePair() {
    return (typeof AppLangPair !== 'undefined') ? AppLangPair.getActive().id : 'es-en';
  }

  // _ID_MAP.vocab is keyed by target language (vocab is target-centric — shared
  // across all pairs that learn the same language).
  function _targetLang() {
    return (typeof AppLangPair !== 'undefined') ? AppLangPair.getActive().target.code : 'en';
  }

  function _migrateCardIds(data) {
    if (!data || !data.cards) return data;
    // The positional→string remap needs _ID_MAP. If it hasn't loaded yet, mark the
    // migration pending and return the data UNCHANGED (v2). _load() then must NOT save
    // (saving bumps _v to 3 = permanent progress loss without the remap). _ensureIdMap()
    // re-runs this once the map arrives. This is the data-loss-proof guard.
    if (!_ID_MAP) { data.__pendingIdMigration = true; return data; }
    delete data.__pendingIdMigration;
    const cards    = data.cards;
    const newCards = {};
    let   changed  = 0;

    Object.keys(cards).forEach(key => {
      if (key.startsWith('_') || key.startsWith('grammar_')) {
        newCards[key] = cards[key]; return;
      }

      // Try to match old positional phrase key: {actPrefix?}{topic}_{number}
      const _byTopic = _mapPhrases(_activePair(), true);
      const phraseTopics = Object.keys(_byTopic);
      let mapped = false;

      for (const act of _PHRASE_ACTS) {
        for (const topic of phraseTopics) {
          const prefix = act + topic + '_';
          if (!key.startsWith(prefix)) continue;
          const rest = key.slice(prefix.length);
          if (!/^\d+$/.test(rest)) continue;  // not numeric → already new format
          const idx = parseInt(rest, 10);
          const ids = _byTopic[topic];
          if (idx >= ids.length) { newCards[key] = cards[key]; mapped = true; break; }
          const newKey = act + ids[idx];
          newCards[newKey] = cards[key];
          if (newKey !== key) changed++;
          mapped = true; break;
        }
        if (mapped) break;
      }

      if (!mapped) {
        // Try vocab key: {quizBase|vocabBase}_{number} (vocab is keyed by target language).
        const _vByTopic = _mapVocab(_targetLang(), true);
        const vocabEntries = Object.values(_vByTopic);
        for (const entry of vocabEntries) {
          for (const base of [entry.quizBase, entry.vocabBase]) {
            const prefix = base + '_';
            if (!key.startsWith(prefix)) continue;
            const rest = key.slice(prefix.length);
            if (!/^\d+$/.test(rest)) continue;
            const idx = parseInt(rest, 10);
            if (idx >= entry.ids.length) { newCards[key] = cards[key]; mapped = true; break; }
            const newKey = base + '_' + entry.ids[idx];
            newCards[newKey] = cards[key];
            if (newKey !== key) changed++;
            mapped = true; break;
          }
          if (mapped) break;
        }
      }

      if (!mapped) newCards[key] = cards[key];
    });

    if (changed > 0) {
      data.cards = newCards;
      data._v = 3;
    }
    return data;
  }

  // ── Migration: traveling/entertainment → split topics ─────────────────
  // traveling and entertainment were split into more specific topics.
  // Old card IDs with those prefixes are orphaned — user re-learns with better scope.

  function _migrateSplitTopics(data) {
    if (!data || !data.cards || data._splitV >= 1) return false;
    const prefixes = ['traveling_', 'entertainment_'];
    const acts     = ['', 'dict_', 'cloze_', 'trans_', 'scramble_'];
    let   changed  = false;
    Object.keys(data.cards).forEach(id => {
      for (const act of acts) {
        for (const p of prefixes) {
          if (id === act + p.slice(0, -1) || id.startsWith(act + p)) {
            delete data.cards[id];
            changed = true;
          }
        }
      }
    });
    data._splitV = 1;
    return true; // always mark as done so we don't re-scan on every load
  }

  // ── Persistence ───────────────────────────────────────────────────────

  let _quotaWarned = false;

  function _showQuotaToast() {
    if (_quotaWarned) return;
    _quotaWarned = true;
    const t = document.createElement('div');
    t.setAttribute('role', 'alert');
    Object.assign(t.style, {
      position: 'fixed', bottom: '1.25rem', left: '50%', transform: 'translateX(-50%)',
      background: '#b91c1c', color: '#fff', borderRadius: '0.5rem',
      padding: '0.6rem 1.1rem', fontSize: '0.85rem', fontWeight: '600',
      zIndex: '10000', boxShadow: '0 4px 16px rgba(0,0,0,.25)',
      maxWidth: '90vw', textAlign: 'center',
    });
    t.textContent = AppLang.t('storage_full');
    document.body?.appendChild(t);
    setTimeout(() => t.remove(), 8000);
  }

  // In-memory cache: the parsed store is read on nearly every interaction and by
  // read-heavy pages (Mi Aprendizaje / Perfil call it dozens of times per render).
  // Parse once, keep it, and let _save keep it in sync. Safe because the only
  // other writers of STORE_KEY (backup import, pair switch) reload the page, which
  // rebuilds this module and its cache from fresh localStorage.
  let _cache = null;
  let _allCardsMemo = null;   // normalized view for getAllCards, invalidated on save

  function _load() {
    if (_cache) return _cache;
    let data;
    try {
      const raw = localStorage.getItem(STORE_KEY);
      if (!raw) {
        data = _migrateLegacy() || { _v: SCHEMA_VERSION, cards: {} };
      } else {
        data = JSON.parse(raw);
        if (!data || typeof data !== 'object') {
          data = { _v: SCHEMA_VERSION, cards: {} };
        } else {
          if (!data.cards) data.cards = {};
          if (!data._v || data._v < 3) {
            data = _migrateCardIds(data);
            if (data.__pendingIdMigration) {
              // id-map not loaded yet — keep v2 data intact and do NOT save (that would
              // bump _v to 3 without the remap). _ensureIdMap() completes it on arrival;
              // meanwhile card lookups are transiently empty (data itself is untouched).
              _ensureIdMap();
            } else {
              _migrateSplitTopics(data);
              _cache = data; _save(data);           // set cache before _save reads it
            }
          } else if (_migrateSplitTopics(data)) {
            _cache = data; _save(data);
          }
        }
      }
    } catch (e) {
      data = { _v: SCHEMA_VERSION, cards: {} };
    }
    _cache = data;
    return data;
  }

  function _save(data) {
    data._v = SCHEMA_VERSION;
    _cache = data;             // keep the in-memory cache authoritative
    _allCardsMemo = null;      // data changed → drop the normalized view
    try { localStorage.setItem(STORE_KEY, JSON.stringify(data)); }
    catch (e) {
      if (e instanceof DOMException && (e.name === 'QuotaExceededError' || e.name === 'NS_ERROR_DOM_QUOTA_REACHED')) {
        _showQuotaToast();
      }
    }
  }

  // ── Card helpers ──────────────────────────────────────────────────────

  function _emptyCard() {
    return { interval: 0, ease: EF_DEFAULT, reps: 0, lapses: 0, due: 0 };
  }

  function getCard(id) {
    const data = _load();
    return data.cards[id] || _emptyCard();
  }

  // ── Variant coverage (multi-form phrases) ─────────────────────────────
  // Each card tracks per-form practice counts (keyed by audioSlug) in an
  // optional `variants` map. Activities rotate to the least-practiced form so
  // every variant (gender/region/register) is guaranteed exposure over
  // repetitions, and coverage is measurable per variant (not just per phrase).
  // The SM-2 schedule still tracks phrase mastery; variant coverage is a soft,
  // separate signal — it does not gate mastery.

  // Return the audio-eligible form the learner has practiced least for this card
  // (ties broken randomly). Falls back to the first form for single-form phrases.
  function pickVariant(id, forms) {
    const pool = (forms || []).filter(f => f && f.audioSlug);
    if (pool.length <= 1) return pool[0] || (forms || [])[0] || null;
    const card   = _load().cards[id];
    const counts = (card && card.variants) || {};
    let min = Infinity;
    for (const f of pool) min = Math.min(min, counts[f.audioSlug] || 0);
    const least = pool.filter(f => (counts[f.audioSlug] || 0) === min);
    return least[Math.floor(Math.random() * least.length)];
  }

  // Record that a form (by audioSlug) was practiced for this card.
  function recordVariant(id, slug) {
    if (!id || !slug) return;
    const data = _load();
    const card = data.cards[id] || _emptyCard();
    card.variants = card.variants || {};
    card.variants[slug] = (card.variants[slug] || 0) + 1;
    data.cards[id] = card;
    _save(data);
  }

  // How many of a phrase's forms have been practiced at least once.
  function getVariantCoverage(id, slugs) {
    const total = (slugs || []).length;
    if (!total) return { practiced: 0, total: 0 };
    const card   = _load().cards[id];
    const counts = (card && card.variants) || {};
    const practiced = slugs.filter(s => (counts[s] || 0) > 0).length;
    return { practiced, total };
  }

  // ── SM-2 rating ───────────────────────────────────────────────────────

  /**
   * Rate a card after review and advance its SM-2 schedule.
   * quality: 1 = Hard/wrong, 3 = OK/correct, 5 = Easy/correct
   */
  function rate(id, quality) {
    const data = _load();
    const card = data.cards[id] || _emptyCard();

    if (quality === 1) {
      card.interval = 1;
      card.ease     = Math.max(EF_MIN, card.ease - EF_HARD_PENALTY);
      card.lapses   = (card.lapses || 0) + 1;
      card.reps     = 0;
    } else if (quality === 3) {
      if (card.reps === 0)      card.interval = 1;
      else if (card.reps === 1) card.interval = 3;
      else                      card.interval = Math.max(1, Math.round(card.interval * card.ease));
      card.ease = Math.max(EF_MIN, card.ease - EF_OK_PENALTY);
    } else {
      if (card.reps === 0)      card.interval = 3;
      else if (card.reps === 1) card.interval = 5;
      else                      card.interval = Math.max(1, Math.round(card.interval * card.ease * EF_EASY_BONUS));
      card.ease = Math.min(EF_MAX, card.ease + EF_EASY_BOOST);
    }

    if (quality >= 3) card.lapses = Math.max(0, (card.lapses || 0) - 1);

    card.reps = (card.reps || 0) + 1;
    card.due  = Date.now() + card.interval * 86_400_000;

    data.cards[id] = card;
    _save(data);
  }

  // ── Visual mastery API ────────────────────────────────────────────────

  /**
   * Translate SM-2 interval → human-readable mastery state.
   * @param {string} id
   * @returns {'new'|'learning'|'practiced'|'mastered'}
   */
  function getMastery(id) {
    const card = getCard(id);
    if (card.reps === 0)       return 'new';
    if (card.interval <= 3)    return 'learning';
    if (card.interval <= 14)   return 'practiced';
    return 'mastered';
  }

  // ── Scheduling ────────────────────────────────────────────────────────

  /**
   * Return the index of the next card to review from cardIds.
   * Priority: due cards (due ≤ now) first, then new cards, then future cards.
   * @param {string[]} cardIds
   * @param {number}   excludeIdx — index to skip (just-reviewed card)
   * @returns {number}
   */
  function getNextIndex(cardIds, excludeIdx) {
    const data = _load();
    const now  = Date.now();
    let bestIdx   = -1;
    let bestScore = Infinity;

    for (let i = 0; i < cardIds.length; i++) {
      if (i === excludeIdx) continue;
      const card = data.cards[cardIds[i]];
      const reps = card ? card.reps : 0;
      const due  = card && card.due ? card.due : 0;

      // Score: 0 = due now (no card yet), 1 = overdue, 2+ = future
      // Within overdue: smaller interval = more urgent
      let score;
      if (reps === 0)      score = 50_000 + i;          // new: show after overdue, stable order
      else if (due <= now) score = card.interval;        // overdue: most urgent first
      else                 score = 100_000 + (due - now) / 86_400_000; // future: soonest first

      if (score < bestScore) { bestScore = score; bestIdx = i; }
    }

    return bestIdx === -1 ? 0 : bestIdx;
  }

  // ── Level ─────────────────────────────────────────────────────────────

  function setLevel(level) {
    const data = _load();
    data.level = level;
    _save(data);
    localStorage.setItem(AppLangPair.storageKey('pe_placement_level'), level);
  }

  function getLevel() {
    const data = _load();
    if (data.level) return data.level;
    return localStorage.getItem(AppLangPair.storageKey('pe_placement_level')) || 'A1';
  }

  // ── Sessions & streak ─────────────────────────────────────────────────

  function recordSession(topic, correct, total) {
    const data = _load();
    if (!data._sessions) data._sessions = [];
    data._sessions.push({
      date: new Date().toLocaleDateString('sv'),
      topic,
      correct,
      total
    });
    if (data._sessions.length > 100) data._sessions.shift();

    const today = new Date().toLocaleDateString('sv');
    const yd = new Date(); yd.setDate(yd.getDate() - 1);
    const yesterday = yd.toLocaleDateString('sv');
    if (!data._streak) data._streak = { current: 0, last: '', best: 0 };
    const s = data._streak;
    if (s.last !== today) {
      s.current = (s.last === yesterday) ? s.current + 1 : 1;
      s.last    = today;
      s.best    = Math.max(s.best, s.current);
    }
    _save(data);
  }

  function getStreak() {
    return _load()._streak || { current: 0, last: '', best: 0 };
  }

  function getSessions() {
    return _load()._sessions || [];
  }

  // ── getAllCards ────────────────────────────────────────────────────────

  /**
   * Returns all card data.
   * Exposes full SM-2 fields + aliases used by older callers:
   *   reps    — correct for all activity files and phrase-browser
   *   lapses  — used by grammar.js checks
   */
  // Read-only normalized view of all cards. Memoized (invalidated in _save) because
  // read-heavy pages call this once per topic — up to ~44× per render. Callers must
  // treat the result as read-only (they all do); mutating it would corrupt the memo.
  function getAllCards() {
    if (_allCardsMemo) return _allCardsMemo;
    const data = _load();
    const out  = {};

    if (data._sessions) out._sessions = data._sessions;
    if (data._streak)   out._streak   = data._streak;

    Object.keys(data.cards).forEach(key => {
      const v = data.cards[key];
      if (!v || typeof v !== 'object') return;
      out[key] = {
        interval: typeof v.interval === 'number' ? v.interval : 0,
        ease:     typeof v.ease     === 'number' ? v.ease     : EF_DEFAULT,
        reps:     typeof v.reps     === 'number' ? v.reps     : 0,
        lapses:   typeof v.lapses   === 'number' ? v.lapses   : 0,
        due:      typeof v.due      === 'number' ? v.due      : 0,
      };
    });

    _allCardsMemo = out;
    return out;
  }

  // ── Stable-ID helpers (v3+) ──────────────────────────────────────────

  /**
   * Return the stable phraseIds for a topic (from the embedded ID map).
   * e.g. getPhraseIds('greetings') → ['greetings_hello_how_are_you_today', ...]
   */
  function getPhraseIds(topicId) {
    const byTopic = _mapPhrases(_activePair(), true);
    return (byTopic[topicId] || []).slice();
  }

  /**
   * Return the stable wordIds for a vocab topic.
   * e.g. getVocabIds('general') → ['abundant', 'accomplish', ...]
   *      getVocabIds('greetings') → ['introduction', 'farewell', ...]
   */
  function getVocabIds(topicId) {
    const byTopic = _mapVocab(_targetLang(), true);
    const entry = byTopic[topicId];
    return (entry && entry.ids) ? entry.ids.slice() : [];
  }

  /**
   * Total content counts for the ACTIVE pair, derived from the embedded ID map
   * (which is kept in sync with the JSON content by fix-phrase-ids.js). Lets the
   * landing page show the real size of each pair instead of a hardcoded number.
   * @returns {{ phrases: number, words: number }}
   */
  function getContentCounts() {
    const ph = _mapPhrases(_activePair(), false);
    let phrases = 0;
    for (const t in ph) phrases += (ph[t] || []).length;
    const vb = _mapVocab(_targetLang(), false);
    let words = 0;
    for (const t in vb) words += ((vb[t] && vb[t].ids) || []).length;
    return { phrases, words };
  }

  /**
   * Count seen cards from an explicit list of card IDs.
   * 'seen' = reps ≥ 1.
   * @param {string[]} ids
   * @returns {{ seen: number, total: number }}
   */
  function getStatsForCards(ids) {
    const data = _load();
    const seen = ids.filter(id => { const c = data.cards[id]; return c && c.reps > 0; }).length;
    return { seen, total: ids.length };
  }

  // Kick off the id-map fetch immediately (non-blocking). For returning users the
  // service worker serves it from cache in ~ms, so any consumer that reads it (the
  // landing stat, path due-counts, the v2→v3 migration) sees it almost at once.
  _ensureIdMap();

  return {
    getCard,
    rate,
    pickVariant,
    recordVariant,
    getVariantCoverage,
    getMastery,
    getNextIndex,
    getPhraseIds,
    getVocabIds,
    getContentCounts,
    getStatsForCards,
    setLevel,
    getLevel,
    recordSession,
    getStreak,
    getSessions,
    getAllCards,
    ensureIdMap: _ensureIdMap,
  };
})();
